// lib/tafsirCorpus.js — Corpus de référence du Tafsir al-Ahlam (interprétation
// des rêves), app/tafsir. Rédigé pour ASRAR PRO — reformulations dans
// l'esprit de la tradition (Ibn Sirîn et consorts), PAS une copie d'un texte
// précis : chaque symbole résume la lecture la plus courante ET rappelle,
// quand la tradition le fait elle-même, que le sens dépend fortement du
// CONTEXTE du rêve (état du rêveur, autres éléments présents, couleur, etc.)
// — l'interprétation onirique n'a jamais été une science exacte à sens
// unique, une liste qui prétendrait le contraire serait malhonnête.
//
// Module partagé (une seule source de vérité), même principe que
// lib/dhikrPresets.js / lib/wafqIntentions.js. `keywords` : formes
// normalisées (lib/tafsirLogic.js normalizeText) utilisées pour la recherche
// et la détection dans un texte libre (« racontez votre rêve »).

export const TAFSIR_CATEGORIES = [
  { id: 'nature', label: 'Éléments naturels', icon: '🌊' },
  { id: 'animaux', label: 'Animaux', icon: '🐍' },
  { id: 'corps', label: 'Corps', icon: '🦷' },
  { id: 'situations', label: 'Situations', icon: '🏃' },
  { id: 'objets', label: 'Objets & lieux', icon: '🗝️' },
  { id: 'personnes', label: 'Personnes', icon: '👥' },
  { id: 'nourriture', label: 'Nourriture', icon: '🍞' },
];

export const TAFSIR_CORPUS = [
  // ── Éléments naturels ──────────────────────────────────────────
  { id: 'eau-claire', category: 'nature', icon: '💧', label: 'Eau claire, limpide', keywords: ['eau claire', 'eau limpide', 'eau pure'],
    interpretation: "Signe de vie saine, de savoir et de foi apaisée. Boire une eau claire annonce souvent un bienfait ou une bonne nouvelle proche." },
  { id: 'eau-trouble', category: 'nature', icon: '🌊', label: 'Eau trouble ou agitée', keywords: ['eau trouble', 'eau sale', 'eau agitee', 'eau boueuse'],
    interpretation: "Évoque des soucis, une situation confuse ou une épreuve passagère. Plus l'eau est agitée, plus l'inquiétude ressentie par le rêveur est grande — sans être nécessairement un mauvais présage définitif." },
  { id: 'mer', category: 'nature', icon: '🌊', label: 'Mer, océan', keywords: ['mer', 'ocean'],
    interpretation: "La mer représente souvent une autorité, un projet vaste ou le monde ici-bas lui-même. Y naviguer sereinement annonce un voyage ou une entreprise réussie ; y être submergé signale une épreuve qui dépasse le rêveur." },
  { id: 'pluie', category: 'nature', icon: '🌧️', label: 'Pluie', keywords: ['pluie', 'averse'],
    interpretation: "Généralement de bon augure : miséricorde, subsistance (rizq) et soulagement après une difficulté — sauf si elle est violente au point de causer des dégâts, où elle se lit alors comme une épreuve collective." },
  { id: 'feu', category: 'nature', icon: '🔥', label: 'Feu', keywords: ['feu', 'incendie', 'flamme'],
    interpretation: "Double lecture traditionnelle : une lumière/chaleur maîtrisée (un foyer, une lampe) annonce un bienfait ou une connaissance ; un feu qui se propage et brûle évoque une discorde, une colère ou une épreuve à venir." },
  { id: 'montagne', category: 'nature', icon: '⛰️', label: 'Montagne', keywords: ['montagne'],
    interpretation: "Symbole de stabilité, de protection ou d'une personne de haute valeur. Gravir une montagne annonce un effort qui mène à une élévation ; en dévaler évoque une perte de position." },
  { id: 'soleil', category: 'nature', icon: '☀️', label: 'Soleil', keywords: ['soleil'],
    interpretation: "Associé à l'autorité, à la gloire ou à une figure importante (souvent un dirigeant ou le père). Un soleil radieux annonce un rayonnement ou une reconnaissance ; un soleil voilé, un affaiblissement de cette autorité." },
  { id: 'lune', category: 'nature', icon: '🌙', label: 'Lune', keywords: ['lune'],
    interpretation: "Évoque souvent une figure d'autorité plus douce (un ministre, une mère, un savant) ou la beauté. La pleine lune est un signe très favorable ; une lune qui décroît annonce un déclin passager." },
  { id: 'etoiles', category: 'nature', icon: '⭐', label: 'Étoiles', keywords: ['etoile', 'etoiles'],
    interpretation: "Représentent des personnes de mérite (savants, guides) ou des enfants. Un ciel étoilé et clair est de bon augure ; une étoile qui tombe annonce la perte d'influence d'une personne importante." },
  { id: 'vent', category: 'nature', icon: '💨', label: 'Vent, tempête', keywords: ['vent', 'tempete', 'orage'],
    interpretation: "Un vent doux porte une bonne nouvelle qui vient de loin. Un vent violent ou une tempête annonce une épreuve soudaine, une rumeur ou un bouleversement." },
  { id: 'arbre', category: 'nature', icon: '🌳', label: 'Arbre', keywords: ['arbre'],
    interpretation: "Symbolise une personne, une lignée ou un projet durable. Un arbre fruitier et verdoyant annonce prospérité et descendance ; un arbre desséché, un déclin ou une rupture de lien." },

  // ── Animaux ────────────────────────────────────────────────────
  { id: 'serpent', category: 'animaux', icon: '🐍', label: 'Serpent', keywords: ['serpent', 'vipere'],
    interpretation: "Très souvent lu comme un ennemi caché, une jalousie ou un danger dissimulé — parfois aussi la richesse ou le pouvoir selon le contexte. Le tuer sans être mordu annonce la victoire sur cet ennemi." },
  { id: 'chat', category: 'animaux', icon: '🐱', label: 'Chat', keywords: ['chat', 'chatte'],
    interpretation: "Évoque un proche du foyer, parfois hypocrite ou opportuniste selon son comportement dans le rêve. Un chat affectueux annonce une aide domestique ; un chat agressif, une trahison de l'entourage proche." },
  { id: 'chien', category: 'animaux', icon: '🐕', label: 'Chien', keywords: ['chien'],
    interpretation: "Peut représenter un gardien fidèle ou, selon la tradition, un ennemi bruyant mais peu dangereux. Un chien qui aboie sans mordre évoque une menace qui reste sans effet." },
  { id: 'lion', category: 'animaux', icon: '🦁', label: 'Lion', keywords: ['lion'],
    interpretation: "Symbole de puissance et d'autorité — souvent un dirigeant ou une personne redoutée. Le voir de loin est un signe de protection ; en être poursuivi annonce une confrontation avec une autorité." },
  { id: 'oiseau', category: 'animaux', icon: '🕊️', label: 'Oiseau, voler', keywords: ['oiseau', 'voler', 'vol', 'voler dans les airs', 'envol'],
    interpretation: "Voler librement et sereinement annonce une élévation de statut ou un soulagement prochain. Un oiseau qui s'échappe des mains évoque une opportunité manquée." },
  { id: 'poisson', category: 'animaux', icon: '🐟', label: 'Poisson', keywords: ['poisson'],
    interpretation: "Lié à la subsistance (rizq) et au gain. Pêcher un gros poisson est un signe de bienfait matériel proche ; un poisson mort annonce une perte financière." },
  { id: 'loup', category: 'animaux', icon: '🐺', label: 'Loup', keywords: ['loup'],
    interpretation: "Évoque un ennemi rusé et déterminé, parfois proche du rêveur sans qu'il le sache encore." },
  { id: 'cheval', category: 'animaux', icon: '🐎', label: 'Cheval', keywords: ['cheval', 'chevaux'],
    interpretation: "Symbole de force, d'honneur et de réussite. Monter un cheval docile annonce une élévation sociale ; un cheval qui se cabre évoque une entreprise difficile à maîtriser." },
  { id: 'corbeau', category: 'animaux', icon: '🐦‍⬛', label: 'Corbeau', keywords: ['corbeau'],
    interpretation: "Traditionnellement associé à une mauvaise nouvelle, une séparation ou un homme malhonnête — à nuancer selon le reste du rêve." },
  { id: 'abeille', category: 'animaux', icon: '🐝', label: 'Abeille', keywords: ['abeille', 'abeilles', 'miel'],
    interpretation: "Signe très favorable : gain licite obtenu par un travail assidu, communauté soudée et bénéfique." },
  { id: 'scorpion', category: 'animaux', icon: '🦂', label: 'Scorpion', keywords: ['scorpion'],
    interpretation: "Évoque une médisance ou un ennemi qui agit dans l'ombre, avec des paroles qui blessent plus que des actes." },
  { id: 'araignee', category: 'animaux', icon: '🕷️', label: 'Araignée', keywords: ['araignee', 'toile'],
    interpretation: "Sa toile symbolise souvent une ruse ou un piège fragile — un projet ou une alliance qui semble solide mais ne l'est pas." },

  // ── Corps ──────────────────────────────────────────────────────
  { id: 'dents', category: 'corps', icon: '🦷', label: 'Dents qui tombent', keywords: ['dent', 'dents', 'dents qui tombent', 'perdre une dent'],
    interpretation: "L'un des rêves les plus rapportés — lu traditionnellement en lien avec la famille proche (une dent = un proche). Une dent qui tombe sans douleur ni sang est plus légère qu'une dent arrachée avec douleur, qui évoque une perte plus lourde à porter." },
  { id: 'cheveux', category: 'corps', icon: '💇', label: 'Cheveux (coupe, chute)', keywords: ['cheveux', 'chute de cheveux', 'coupe de cheveux', 'se raser la tete'],
    interpretation: "Couper ses cheveux volontairement peut annoncer un allègement de dettes ou de soucis. Une chute de cheveux non désirée évoque plutôt une perte de biens ou de prestige." },
  { id: 'mains', category: 'corps', icon: '✋', label: 'Mains', keywords: ['main', 'mains'],
    interpretation: "Les mains représentent l'action et le soutien. Des mains fortes et propres annoncent une aide efficace ; des mains coupées ou sales évoquent une incapacité passagère à agir ou un gain illicite." },
  { id: 'sang', category: 'corps', icon: '🩸', label: 'Sang', keywords: ['sang', 'saigner'],
    interpretation: "Le sang évoque souvent un gain matériel, parfois lié à une situation douteuse — à distinguer d'une blessure qui, elle, annonce une épreuve morale plutôt que physique." },
  { id: 'yeux', category: 'corps', icon: '👁️', label: 'Yeux', keywords: ['yeux', 'oeil', 'aveugle'],
    interpretation: "Des yeux clairs et voyants bien annoncent une bonne direction dans la vie et une foi affermie ; devenir aveugle dans le rêve évoque un égarement passager ou une vérité qu'on refuse de voir." },
  { id: 'nudite', category: 'corps', icon: '🫣', label: 'Être nu en public', keywords: ['nu', 'nudite', 'tout nu'],
    interpretation: "Très souvent lié à la crainte d'être exposé, d'un secret révélé ou d'une honte publique — le sentiment ressenti pendant le rêve (gêne ou indifférence) oriente fortement la lecture." },

  // ── Situations ─────────────────────────────────────────────────
  { id: 'poursuite', category: 'situations', icon: '🏃', label: 'Être poursuivi', keywords: ['poursuivi', 'course poursuite', 'fuir', 'etre poursuivi'],
    interpretation: "Évoque une angoisse, une dette ou une responsabilité que le rêveur cherche à fuir dans la vie éveillée. Échapper au poursuivant est de bon augure ; être rattrapé annonce que la difficulté finira par rattraper le rêveur." },
  { id: 'chute', category: 'situations', icon: '🕳️', label: 'Chuter, tomber', keywords: ['tomber', 'chute', 'chuter dans le vide'],
    interpretation: "Une chute annonce généralement une baisse de statut, un échec passager ou une perte de contrôle sur une situation — se réveiller avant l'impact est courant et n'aggrave pas la lecture." },
  { id: 'mariage', category: 'situations', icon: '💍', label: 'Se marier', keywords: ['mariage', 'se marier', 'noces'],
    interpretation: "Peut annoncer, selon l'état du rêveur, une union réelle à venir — ou plus largement un nouvel engagement (un projet, une étape de vie) qui commence." },
  { id: 'mort', category: 'situations', icon: '⚰️', label: 'Mourir, sa propre mort', keywords: ['mourir', 'ma mort', 'je meurs', 'mort du reveur'],
    interpretation: "Contrairement à l'intuition, se voir mourir soi-même est le plus souvent lu comme une annonce de CHANGEMENT profond ou de repentir, rarement comme un présage littéral de décès." },
  { id: 'accouchement', category: 'situations', icon: '👶', label: 'Accoucher', keywords: ['accoucher', 'accouchement', 'naissance'],
    interpretation: "Annonce l'aboutissement d'un projet porté depuis longtemps — la nature de ce qui « naît » dans le reste du rêve précise si l'issue est heureuse ou pénible." },
  { id: 'perdu', category: 'situations', icon: '🧭', label: 'Être perdu', keywords: ['perdu', 'me perdre', 'perdre son chemin'],
    interpretation: "Évoque une hésitation réelle face à un choix de vie, ou l'éloignement passager d'une pratique/valeur importante pour le rêveur." },
  { id: 'nager', category: 'situations', icon: '🏊', label: 'Nager', keywords: ['nager', 'natation'],
    interpretation: "Nager avec aisance annonce que le rêveur traverse ses difficultés avec succès ; se débattre en nageant évoque un effort qui peine encore à porter ses fruits." },
  { id: 'course-immobile', category: 'situations', icon: '🐢', label: 'Courir sans avancer', keywords: ['courir sans avancer', 'jambes lourdes', 'ne pas avancer'],
    interpretation: "Évoque une impression de blocage ou d'efforts qui ne portent pas encore leurs fruits — la frustration ressentie dans la vie éveillée face à une situation qui traîne." },
  { id: 'escalier', category: 'situations', icon: '🪜', label: 'Monter un escalier', keywords: ['escalier', 'monter les marches', 'gravir'],
    interpretation: "Monter annonce une progression, sociale ou spirituelle, souvent obtenue par étapes ; descendre évoque un renoncement ou un recul volontaire." },
  { id: 'pont', category: 'situations', icon: '🌉', label: 'Traverser un pont', keywords: ['pont', 'traverser un pont'],
    interpretation: "Le pont symbolise une transition, un passage d'une étape de vie à une autre. Le traverser sans encombre annonce que ce passage se fera sans grande difficulté." },
  { id: 'retard', category: 'situations', icon: '⏰', label: 'Être en retard, rater quelque chose', keywords: ['retard', 'rater le train', 'rater lavion', 'en retard'],
    interpretation: "Traduit souvent une anxiété réelle face à une occasion qu'on craint de laisser passer dans la vie éveillée." },
  { id: 'examen', category: 'situations', icon: '📝', label: 'Passer un examen', keywords: ['examen', 'controle', 'evaluation'],
    interpretation: "Évoque une épreuve d'évaluation à venir, réelle ou symbolique — le sentiment de préparation (ou non) ressenti dans le rêve reflète souvent celui vécu à l'éveil." },
  { id: 'prison', category: 'situations', icon: '🔒', label: 'Être emprisonné', keywords: ['prison', 'emprisonne', 'enferme'],
    interpretation: "Symbolise une contrainte, un engagement pesant (dette, promesse, situation subie) dont le rêveur cherche à se libérer." },

  // ── Objets & lieux ─────────────────────────────────────────────
  { id: 'argent', category: 'objets', icon: '💰', label: 'Argent, or', keywords: ['argent', 'or', 'piece dor', 'richesse'],
    interpretation: "Trouver de l'argent ou de l'or est généralement de bon augure pour la subsistance — l'or, en particulier, est parfois lu comme un souci ou une charge selon le contexte (une lecture ancienne, à nuancer)." },
  { id: 'miroir', category: 'objets', icon: '🪞', label: 'Miroir', keywords: ['miroir', 'reflet'],
    interpretation: "Représente souvent l'épouse, un proche fidèle, ou l'image que le rêveur a de lui-même. Un miroir brisé évoque une rupture ou une perte de repère." },
  { id: 'cle', category: 'objets', icon: '🗝️', label: 'Clé', keywords: ['cle', 'cles'],
    interpretation: "Symbole d'ouverture (fath) — une solution, une porte de sortie ou une opportunité qui s'apprête à se présenter." },
  { id: 'epee', category: 'objets', icon: '⚔️', label: 'Épée', keywords: ['epee', 'sabre'],
    interpretation: "Associée à la force, la victoire ou parfois la descendance masculine, selon la tradition. La brandir sans l'utiliser annonce un pouvoir en réserve." },
  { id: 'livre', category: 'objets', icon: '📖', label: 'Livre, Coran', keywords: ['livre', 'coran', 'lire'],
    interpretation: "Lire un livre annonce un savoir à acquérir ou une guidance qui approche. Tenir le Coran avec respect est un signe très favorable de droiture retrouvée." },
  { id: 'echelle', category: 'objets', icon: '🪜', label: 'Échelle', keywords: ['echelle'],
    interpretation: "Comme l'escalier, évoque une progression — mais souvent plus abrupte ou plus risquée, selon sa stabilité dans le rêve." },
  { id: 'maison', category: 'objets', icon: '🏠', label: 'Maison (neuve ou en ruine)', keywords: ['maison', 'maison neuve', 'maison en ruine', 'demenager'],
    interpretation: "La maison représente le rêveur lui-même ou sa situation de vie. Une maison neuve et solide annonce un renouveau ; une maison qui s'effondre évoque une inquiétude pour sa propre stabilité." },
  { id: 'porte', category: 'objets', icon: '🚪', label: 'Porte', keywords: ['porte', 'porte fermee', 'porte ouverte'],
    interpretation: "Une porte ouverte annonce une opportunité accessible ; une porte fermée ou verrouillée évoque un obstacle temporaire, pas nécessairement définitif." },
  { id: 'tombeau', category: 'objets', icon: '🪦', label: 'Tombeau, cimetière', keywords: ['tombeau', 'cimetiere', 'tombe'],
    interpretation: "Peut évoquer, selon le contexte, un lieu de repos pour une affaire agitée (une dette apaisée) ou un rappel à se rapprocher de sa pratique religieuse." },
  { id: 'lampe', category: 'objets', icon: '🪔', label: 'Lampe, lumière', keywords: ['lampe', 'lumiere', 'bougie'],
    interpretation: "Une lumière qui éclaire annonce guidance, savoir ou une naissance proche. Une lumière qui s'éteint évoque la perte d'un soutien ou d'un espoir." },
  { id: 'bijoux', category: 'objets', icon: '💎', label: 'Bijoux', keywords: ['bijoux', 'collier', 'bague'],
    interpretation: "Souvent associés à la beauté d'un accomplissement ou d'un mariage — porter des bijoux volés ou empruntés en revanche évoque un mérite qui n'est pas réellement le sien." },
  { id: 'vetement-blanc', category: 'objets', icon: '👘', label: 'Vêtement blanc, propre', keywords: ['vetement blanc', 'habit blanc', 'vetements propres'],
    interpretation: "Signe très favorable : pureté, bonne réputation et droiture reconnue par l'entourage." },
  { id: 'vetement-dechire', category: 'objets', icon: '🥼', label: 'Vêtement déchiré, sale', keywords: ['vetement dechire', 'habit sale', 'vetements dechires'],
    interpretation: "Évoque une réputation entachée, un secret dévoilé ou une perte de biens, selon l'ampleur des dégâts sur le vêtement." },

  // ── Personnes ──────────────────────────────────────────────────
  { id: 'defunt', category: 'personnes', icon: '🕊️', label: 'Voir un défunt', keywords: ['defunt', 'personne decedee', 'mort qui parle', 'voir un mort'],
    interpretation: "Voir un proche défunt en bonne santé et souriant est traditionnellement lu comme un bon signe pour lui (et pour le rêveur) ; le voir triste ou en difficulté invite à faire des invocations et des aumônes pour lui." },
  { id: 'foule', category: 'personnes', icon: '👥', label: 'Foule', keywords: ['foule', 'beaucoup de gens'],
    interpretation: "Évoque une agitation sociale, une nouvelle qui circule vite, ou pour le rêveur lui-même un besoin d'appartenance à un groupe." },
  { id: 'ennemi', category: 'personnes', icon: '⚔️', label: 'Affronter un ennemi', keywords: ['ennemi', 'adversaire', 'affronter quelquun'],
    interpretation: "Le vaincre dans le rêve annonce la résolution d'un conflit réel ; être dominé par lui invite à la prudence dans une relation tendue de la vie éveillée." },
  { id: 'bebe', category: 'personnes', icon: '👶', label: 'Voir un bébé', keywords: ['bebe', 'nourrisson'],
    interpretation: "Annonce généralement un nouveau projet, une nouvelle qui vient de naître dans la vie du rêveur — pas nécessairement une naissance littérale." },
  { id: 'mariee', category: 'personnes', icon: '👰', label: 'Voir une mariée', keywords: ['mariee', 'epousee'],
    interpretation: "Une mariée joyeuse et parée annonce un heureux événement proche ; une mariée en pleurs évoque une union ou un projet qui inquiète le rêveur." },

  // ── Nourriture ─────────────────────────────────────────────────
  { id: 'pain', category: 'nourriture', icon: '🍞', label: 'Pain', keywords: ['pain'],
    interpretation: "Symbole direct de la subsistance quotidienne (rizq) — en manger à sa faim est un signe de bienfait assuré." },
  { id: 'fruits', category: 'nourriture', icon: '🍇', label: 'Fruits', keywords: ['fruits', 'fruit'],
    interpretation: "Des fruits mûrs et savoureux annoncent le fruit d'un effort qui arrive à maturité ; des fruits verts ou pourris évoquent une entreprise encore prématurée ou déjà compromise." },
  { id: 'miel', category: 'nourriture', icon: '🍯', label: 'Miel', keywords: ['miel'],
    interpretation: "Très favorable : douceur de vie, gain licite et parole bienfaisante (le Coran lui-même associe le miel à la guérison)." },
  { id: 'lait', category: 'nourriture', icon: '🥛', label: 'Lait', keywords: ['lait'],
    interpretation: "Associé à la pureté de la foi (le Prophète ﷺ l'a lui-même interprété ainsi) et à une subsistance saine et licite." },
  { id: 'viande', category: 'nourriture', icon: '🍖', label: 'Viande', keywords: ['viande'],
    interpretation: "Selon la tradition, la viande crue peut évoquer la médisance (« manger la chair » d'autrui) ; la viande cuite et partagée annonce un gain licite obtenu avec effort." },
];
